<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    
    <parent>
        <groupId>uno.anahata</groupId>
        <artifactId>anahata-pom</artifactId>
        <version>25.0.0-SNAPSHOT</version>
    </parent>
    
    
    <artifactId>anahata-os-pom</artifactId>
    
    <packaging>pom</packaging>
    
    <name>anahata-os-pom</name>    
    
    <description>Parent pom for Anahata OS projects</description>

    <repositories>
        <repository>
            <id>sonatype-snapshots</id>
            <url>https://central.sonatype.com/repository/maven-snapshots/</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>
    
    <profiles>
        <profile>
            <id>publish</id>
            <build>    
                <plugins>
                    <plugin>
                        <artifactId>maven-resources-plugin</artifactId>
                        <version>3.3.1</version>
                        <executions>
                            <execution>
                                <id>publish-resources-versioned</id>
                                <phase>post-site</phase>
                                <goals>
                                    <goal>copy-resources/</goal>
                                </goals>
                                <configuration>
                                    <outputDirectory>../../anahata-website/workspace/${project.artifactId}/${project.version}</outputDirectory>
                                    <resources>
                                        <resource>
                                            <directory>target/staging/${project.artifactId}</directory>
                                            <filtering>true</filtering>
                                        </resource>
                                    </resources>
                                </configuration>
                            </execution>
                            <execution>
                                <id>publish-resources-latest</id>
                                <phase>post-site</phase>
                                <goals>
                                    <goal>copy-resources</goal>
                                </goals>
                                <configuration>
                                    <outputDirectory>../../anahata-website/workspace/${project.artifactId}/latest</outputDirectory>
                                    <resources>
                                        <resource>
                                            <directory>target/staging/${project.artifactId}</directory>
                                            <filtering>true</filtering>
                                        </resource>
                                    </resources>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-site-plugin</artifactId>
                        <version>3.21.0</version>
                        <configuration>
                        </configuration>                        
                    </plugin>
                </plugins>
            </build>
        </profile>
        
        <profile>
            <id>release</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.sonatype.central</groupId>
                        <artifactId>central-publishing-maven-plugin</artifactId>
                        <version>0.10.0</version>
                        <extensions>true</extensions>
                        <configuration>
                            <publishingServerId>sonatype-central</publishingServerId>
                            <tokenAuth>true</tokenAuth>
                            <autoPublish>true</autoPublish>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-source-plugin</artifactId>
                        <version>3.3.1</version>
                        <executions>
                            <execution>
                                <id>attach-sources</id>
                                <goals>
                                    <goal>jar-no-fork</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-javadoc-plugin</artifactId>
                        <version>3.12.0</version>
                        <executions>
                            <execution>
                                <id>attach-javadocs</id>
                                <goals>
                                    <goal>jar</goal>
                                </goals>
                                <configuration>
                                    <failOnError>false</failOnError>
                                    <docfilessubdirs>true</docfilessubdirs>
                                    <detectJavaApiLink>true</detectJavaApiLink>
                                    <detectOfflineLinks>true</detectOfflineLinks>
                                    <show>private</show>
                                    <top><![CDATA[
        <link rel="stylesheet" type="text/css" href="https://anahata-os.github.io/anahata-os-pom/anahata-barca-theme.css" />
        <img referrerpolicy="no-referrer-when-downgrade" src="https://static.scarf.sh/a.png?x-pxid=f19c44f5-8b2e-458f-beab-96e4f9f8e603" />
        <div class="anahata-footer">
            <img src="https://www.anahata.uno/assets/logo-transparent.png" alt="Anahata Logo" class="anahata-logo">
            <a href="https://github.com/sponsors/anahata-os" target="_blank" class="donate-link">
                Give everything to Anahata ❤️
            </a>
            <div class="barca-wrapper">
                <span class="forca-text">Força <span class="barca-red">Barça!</span></span>
                <img src="https://upload.wikimedia.org/wikipedia/en/4/47/FC_Barcelona_%28crest%29.svg" alt="Barça Crest">
            </div>
        </div>
    ]]></top>
                                    <bottom><![CDATA[
        <div class="anahata-footer">
            <img src="https://www.anahata.uno/assets/logo-transparent.png" alt="Anahata Logo" class="anahata-logo">
            <a href="https://github.com/sponsors/anahata-os" target="_blank" class="donate-link">
                Support the aliens ❤️
            </a>
            <div class="barca-wrapper">
                <span class="forca-text">Força <span class="barca-red">Barça!</span></span>
                <img src="https://upload.wikimedia.org/wikipedia/en/4/47/FC_Barcelona_%28crest%29.svg" alt="Barça Crest">
            </div>
        </div>
        <p class="legal-copy"><small>Nomatter what people say in the future, Messi will always be the best of all times</small></p>
    ]]></bottom>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-gpg-plugin</artifactId>
                        <version>3.2.7</version>
                        <executions>
                            <execution>
                                <id>sign-artifacts</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>sign</goal>
                                </goals>
                            </execution>
                        </executions>
                        <configuration>
                            <gpgArguments>
                                <arg>--pinentry-mode</arg>
                                <arg>loopback</arg>
                            </gpgArguments>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>        
    </profiles>
</project>
