name: Deploy OS Parent POM Artifacts

on:
  push:
    branches: [ "master", "main" ]
    tags:
      - 'v*'
  repository_dispatch:
    types: [ upstream-pom-updated ]
  workflow_dispatch:

jobs:
  deploy:
    name: Build & Publish OS Parent POM
    uses: anahata-os/anahata-pom/.github/workflows/shared-maven-build.yml@master
    secrets: inherit

  trigger-downstream:
    needs: deploy
    name: Trigger Downstream Build
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Downstream Build in anahata-util
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: anahata-os/anahata-util
          event-type: upstream-pom-updated
        continue-on-error: true
